name: AI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: AI Code Review
    steps:
      - name: AI Code Review
        uses: azizultex/chatgpt-github-actions@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "gpt-3.5-turbo-16k" #gpt-4, gpt-3.5-turbo, gpt-3.5-turbo-16k
          openai_temperature: 1 #optional
          openai_max_tokens: 4096 #optional
          file_extensions: ".php,.js"
          mode: patch # files or patch 
          prompt_text: |
            You're an expert programmer. You know a wide range of programming. 
            Now, I will provide you some code from a Github pul request. 
            You will review all the issues in the code below and provide possible solutions. 

            CODE START HERE: 

            {code}
